### ISSUE TITLE
Game testing and Debugging

### ISSUE THREAD

**Issue by jrk823** [MaasRM/Zelda_Project_3902#40]
Time worked:
Jake: 4/21 - 3 hours
Jake: 4/22 - 2 hours
Jake: 4/23 - 2 hours
Phil: 4/23 - 2 hours

**Comment by schultz722** [comment]
Nathan: 4/23 2 hours

**Comment by JaeZee** [comment]
Jared 4/21 - 4 hours
         4/22 - 2 hours
